#!/bin/sh

# general settings
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	mkd="mkdir -pv" \
	ucon="ansible-playbook --ask-become-pass ~/.config/ansible/update.yml"

# Colorize commands
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \

# Common commands
alias \
	ka="killall" \
	g="git" \
	f="$FILE" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="sudo pacman" \
	yv="youtube-dl -4 -f bestvideo+bestaudio" \
	ya="youtube-dl -4 --extract-audio --audio-format mp3 --audio-quality 0 -l" \
