#! /bin/sh

bspc rule -r "*"

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 1
bspc config window_gap 10
bspc config top_padding 24
bspc config focus_follows_pionter true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' follow=on
bspc rule -a Brave-browser desktop='^2' follow=on
bspc rule -a Thunderbird desktop='^3' follow=on
bspc rule -a Pcmanfm desktop='^6' follow=on
bspc rule -a Soffice desktop='^7' follow=on
bspc rule -a Zathura state=tiled
bspc rule -a Plexamp state=floating rectangle=275x400+1405+650 manage=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh
