#! /bin/sh

bspc rule -r "*"

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width 1
bspc config window_gap 10
bspc config top_padding 24
bspc config focus_follows_pionter true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^2'
bspc rule -a Geany desktop='^3'
bspc rule -a Screenkey manage=off
